/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.think.facturas;

import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.think.dao.DaoCliente;
import org.think.dao.DaoProducto;
import org.think.dto.DtoCliente;
import org.think.dto.DtoProducto;

/**
 *
 * @author Marcos Nunez
 */
public class Busqueda1 extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    private int buscar = 0;
    
    DaoCliente cliente;
    DaoProducto producto;
    
    DtoCliente dtCliente;
    DtoProducto dtoProducto;
    
    Facturar facturar;
    
    /**
     * Creates new form Busqueda
     *
     * */

    public Busqueda1(Facturar f) {
      //  super(title, resizable, closable, maximizable, iconifiable);
        initComponents();
       //txtBuscar.requestFocus();
      // model = new DefaultTableModel();  
       facturar = f;
       
 
    }



    /**g
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBuscar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbHasta = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        lbHasta1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Busqueda");
        setToolTipText("");
        setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lbBuscar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbBuscar.setText("Buscar: ");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 153));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRequestFocusEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lbHasta.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbHasta.setText("Hasta: ");

        txtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(255, 255, 153));
        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        lbHasta1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbHasta1.setText("Total: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbBuscar)
                .addGap(185, 185, 185)
                .addComponent(lbHasta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbHasta1)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscar)
                    .addComponent(lbHasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHasta1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscar();
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       
        int selectRow = jTable1.getSelectedRow();
        switch(buscar){
            
            case 1: 
                
                dtCliente = new DtoCliente();
                dtCliente.setIdcliente((Integer)model.getValueAt(selectRow, 0));
                dtCliente.setNombre((String)model.getValueAt(selectRow, 1));
                dtCliente.setDireccion((String)model.getValueAt(selectRow, 2));
                dtCliente.setFecha_registrado((Timestamp)model.getValueAt(selectRow, 3));
                
                facturar.datosCliente(dtCliente);
                break;
                
                
            case 2:
                
                dtoProducto = new DtoProducto();
                dtoProducto.setIdproducto((Integer)model.getValueAt(selectRow, 0));
                dtoProducto.setDescripcion((String)model.getValueAt(selectRow, 1));
                dtoProducto.setPrecio(Float.parseFloat(model.getValueAt(selectRow, 2).toString()));
                dtoProducto.setCantidad((Integer)model.getValueAt(selectRow, 3));                
                dtoProducto.setCosto(Float.parseFloat(model.getValueAt(selectRow, 4).toString()));               
                dtoProducto.setItbis(Float.parseFloat(model.getValueAt(selectRow, 5).toString()));
                dtoProducto.setMin_porc(Float.parseFloat(model.getValueAt(selectRow, 6).toString()));
                
                //showMessageDialog(this, "me ejecuto lala");
                
                facturar.datosProducto(dtoProducto);
                break;
        }
        
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    public void setFocus(){
        this.txtBuscar.requestFocus();
    }
    
    public void buscar(int i){
        this.buscar = i;
    }
    
   private void buscar(){
       
       String abuscar = txtBuscar.getText();
       model = new DefaultTableModel(); 
       
       switch(buscar){
       
           case 1:
               try{
                   cliente = new DaoCliente();
                   model = cliente.getBusquedaForCliente(abuscar);
                    
               }catch(SQLException e){
                   JOptionPane.showMessageDialog(this, e.getMessage());
               }
               break;
               
           case 2: 
               try{
                   producto = new DaoProducto();
                   model = producto.getBusquedaForProducto(abuscar);
    
               }catch(SQLException e){
                   JOptionPane.showMessageDialog(this, e.getMessage());
               }              
               break;   
       }
      jTable1.setModel(model);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbHasta;
    private javax.swing.JLabel lbHasta1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
